apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp-config
  namespace: streaming-poc
data:
  nginx.conf: |
    worker_processes auto;
    rtmp_auto_push on;
    events {
      worker_connections 1024;
    }
    
    rtmp {
      server {
        listen 1935;
        chunk_size 4096;
        
        application live {
          live on;
          record off;
          
          # Notificar al backend cuando inicia un stream
          on_publish http://streaming-api:8000/api/rtmp/auth;
          on_publish_done http://streaming-api:8000/api/rtmp/done;
          
          # Push to transcoder
          push rtmp://transcoder:1935/transcode;
        }
      }
    }
    
    http {
      server {
        listen 8080;
        
        location /stat {
          rtmp_stat all;
          rtmp_stat_stylesheet stat.xsl;
        }
        
        location /stat.xsl {
          root /usr/local/nginx/html;
        }
        
        location /health {
          return 200 "OK\n";
          add_header Content-Type text/plain;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  namespace: streaming-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: alfg/nginx-rtmp:latest
        ports:
        - containerPort: 1935
          name: rtmp
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-rtmp-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
  namespace: streaming-poc
spec:
  type: NodePort
  selector:
    app: nginx-rtmp
  ports:
  - port: 1935
    targetPort: 1935
    nodePort: 31935
    name: rtmp
  - port: 8080
    targetPort: 8080
    name: http